document.write('<meta http-equiv="Content-Type" content="text/html; charset=utf-8">');
document.write('<link href="http://www.meta.vn/client/textlink/300/css/styleTab.css" rel="stylesheet" type="text/css">');
document.write(' ');
document.write('<div class="TabTextlink">');
document.write('<div class="TextLink-Head">');
document.write('<table width="257" border="0" cellpadding="0" cellspacing="0" class="TL-Head-top">');
document.write('<tbody>');
document.write('<tr>');
document.write('<td width="81"><a href="http://meta.vn/"><img src="http://img.meta.com.vn/client/textlink/300/images/logo.jpg" border="0"></a></td>');
document.write('<td width="126" style="text-align:center; font-weight:bold; color:#dc342f">');
document.write('<a href="http://meta.vn/">www.meta.vn<br>');
document.write('Mua sắm trực tuyến</a>');
document.write('  </td>');
document.write('<td width="50"><img src="http://img.meta.com.vn/client/textlink/300/images/hand-icon.jpg"></td>');
document.write('</tr>');
document.write('</tbody>');
document.write('  </table>');
document.write('</div>');
document.write('<div class="TextLink-body"><div class="Textlink-item">');
document.write('<div class="itemsTL">');
document.write('<div class="itemsTl-top">');
document.write('<div class="itemsTL-catalog"><a href="http://meta.vn/giadung/">Đồ gia dụng</a></div>');
document.write('<div class="linkweb"><a href="http://meta.vn/giadung/">www.meta.vn</a></div>');
document.write('</div>');
document.write('<div>');
document.write('<table border="0" cellpadding="0" cellspacing="0">');
document.write('<tbody>');
document.write('<tr>');
document.write('<td style=" width:105px; border:1px solid #e1e1e1;"><a href="http://meta.vn/giadung/"><img src="http://img.meta.com.vn/client/textlink/300/images/giadung.jpg" border="0"></a></td>');
document.write('<td class="itemsTL-intro" valign="top"><a href="http://meta.vn/giadung/">Đồ dùng nhà bếp, máy trồng rau mầm, máy làm sữa chua, máy pha cà phê, chổi lau nhà 360, ... Tất cả có tại META.vn</a></td>');
document.write('</tr>');
document.write('</tbody>');
document.write('</table>');
document.write('</div>');
document.write('</div>');
document.write('</div><div class="Textlink-item">');
document.write('<div class="itemsTL">');
document.write('<div class="itemsTl-top">');
document.write('<div class="itemsTL-catalog"><a href="http://meta.vn/thietbivanphong/">Thiết bị văn phòng</a></div>');
document.write('<div class="linkweb"><a href="http://meta.vn/thietbivanphong/">www.meta.vn</a></div>');
document.write('</div>');
document.write('<div>');
document.write('<table border="0" cellpadding="0" cellspacing="0">');
document.write('<tbody>');
document.write('<tr>');
document.write('<td style=" width:105px; border:1px solid #e1e1e1;"><a href="http://meta.vn/thietbivanphong/"><img src="http://img.meta.com.vn/client/textlink/300/images/vanphong.jpg" border="0"></a></td>');
document.write('<td class="itemsTL-intro" valign="top"><a href="http://meta.vn/thietbivanphong/">Máy in đa năng, máy chiếu, máy fax, máy đếm tiền. Thiết bị văn phòng các loại</a></td>');
document.write('</tr>');
document.write('</tbody>');
document.write('</table>');
document.write('</div>');
document.write('</div>');
document.write('</div><div class="Textlink-item">');
document.write('<div class="itemsTL">');
document.write('<div class="itemsTl-top">');
document.write('<div class="itemsTL-catalog"><a href="http://meta.vn/phanmem/">Phần mềm bản quyền</a></div>');
document.write('<div class="linkweb"><a href="http://meta.vn/phanmem/">www.meta.vn</a></div>');
document.write('</div>');
document.write('<div>');
document.write('<table border="0" cellpadding="0" cellspacing="0">');
document.write('<tbody>');
document.write('<tr>');
document.write('<td style=" width:105px; border:1px solid #e1e1e1;"><a href="http://meta.vn/phanmem/"><img src="http://img.meta.com.vn/client/textlink/300/images/phanmem.jpg" border="0"></a></td>');
document.write('<td class="itemsTL-intro" valign="top"><a href="http://meta.vn/phanmem/">Phần mềm diệt virus, PM văn phòng, PM giáo dục, PM học tiếng anh. Hãy sở hữu phần mềm bản quyền ngay bây giờ!</a></td>');
document.write('</tr>');
document.write('</tbody>');
document.write('</table>');
document.write('</div>');
document.write('</div>');
document.write('</div></div>');
document.write('</div>');
